[package]
name = "open-gpki-pkcs11"
version = "0.1.1"
edition = "2021"
description = "Standalone PKCS#11 module for Taiwan GPKI smart cards"
license = "LGPL-2.1-or-later"

[lib]
crate-type = ["cdylib", "rlib"]
name = "open_gpki_pkcs11"

[dependencies]
aes = "0.8"
cipher = "0.4"
cmac = "0.7"
des = "0.9.0"
getrandom = "0.4.3"
md-5 = "0.10"
num-bigint = "0.5.1"
pcsc = "2.8"
sha1 = "0.10"
sha2 = "0.10"

[profile.release]
lto = false
codegen-units = 16
